# Implemented test modules:
test_names = {"activation": ["td_lorawan_act_01",
                             "td_lorawan_act_02",
                             "td_lorawan_act_03",
                             "td_lorawan_act_04",
                             "td_lorawan_act_05"],
              "functionality": ["td_lorawan_fun_01",
                                "td_lorawan_fun_02",
                                "td_lorawan_fun_03",
                                "td_lorawan_fun_04",
                                "td_lorawan_fun_05",
                                "td_lorawan_fun_06"],
              "security": ["td_lorawan_sec_01",
                           "td_lorawan_sec_02"],
              "mac_commands": ["td_lorawan_mac_01",
                               "td_lorawan_mac_02",
                               "td_lorawan_mac_03",
                               "td_lorawan_mac_04",
                               "td_lorawan_mac_05"],
              "general": ["td_lorawan_deactivate",
                          "td_lorawan_reset"]}
