version: '3'

volumes:
  volume_message-broker:
  volume_postgres:


services:
  tools-config-scheduler:
    depends_on:
      - message-broker
      - postgres
    image: "${DOCKER_REPO}/tools-config-scheduler:${TOOLS_CS_VERSION}"
    volumes:
      - ./downlink_scheduler_tool/devices_data.py:/config_scheduler/downlink_scheduler_tool/devices_data.py
      - ./downlink_scheduler_tool/devices_sessions.py:/config_scheduler/downlink_scheduler_tool/devices_sessions.py
      - ./downlink_scheduler_tool/downlink_scheduler.py:/config_scheduler/downlink_scheduler_tool/downlink_scheduler.py
    environment:
      - "AMQP_URL=${AMQP_URL}"
    env_file:
      - env_var
    restart: on-failure
    command: ["python3", "/config_scheduler/downlink_scheduler_tool/config_scheduler_main.py"]

  tools-agent-scheduler:
    depends_on:
      - message-broker
    image: "${DOCKER_REPO}/tools-agent-scheduler:${TOOLS_AS_VERSION}"
    volumes:
      - ./lorawan/user_agent/bridge/agent_bridge.py:/agent_mock/lorawan/user_agent/bridge/agent_bridge.py
    environment:
      - "AMQP_URL=${AMQP_URL}"
    env_file:
      - env_var
    expose:
      - "1700"
    ports:
      - "${AGENT_SCHEDULER_PORT}:1700/udp"
    restart: on-failure
    command: ["python3", "/agent_mock/lorawan/user_agent/bridge/bridge_main.py"]
